== Installing CI builds of Red Hat Developer Hub

=== Installing the Operator

==== Prerequisites

Regardless of the cluster provider, you will need the following tools:

* `GNU grep`. See link:https://www.gnu.org/software/grep/[GNU grep].
* `jq`. See link:https://jqlang.github.io/jq/download/[Download jq].
* `opm`. See link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/cli_tools/opm-cli[opm CLI].
* `GNU sed`. See link:https://www.gnu.org/software/sed/[GNU sed].
* `Skopeo`. See link:https://github.com/containers/skopeo/blob/main/install.md[Installing Skopeo].

===== OpenShift

Besides the prerequisites listed above, you will also need:

* `oc`. See link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/cli_tools/openshift-cli-oc#cli-installing-cli_cli-developer-commands[Installing the OpenShift CLI].
* A login as an administrator using `oc login`. See link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/cli_tools/openshift-cli-oc#cli-logging-in_cli-developer-commands[Logging in to the OpenShift CLI] or link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/cli_tools/openshift-cli-oc#cli-logging-in-web_cli-developer-commands[Logging in to the OpenShift CLI using a web browser].
* `umoci` (used if the script detects that the cluster has a hosted control plane). See link:https://github.com/opencontainers/umoci#install[Install].

===== Kubernetes

Besides the prerequisites listed above, you will also need:

* `base64`
* link:https://kubernetes.io/docs/tasks/tools/#kubectl[`kubectl`] or link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/cli_tools/openshift-cli-oc#cli-installing-cli_cli-developer-commands[`oc`]
* Operator Lifecycle Manager (OLM). See link:https://olm.operatorframework.io/docs/getting-started/#installing-olm-in-your-cluster[Installing OLM in your cluster].
* link:https://www.gnu.org/software/tar/[`GNU tar`]
* `umoci`. See link:https://github.com/opencontainers/umoci#install[Install].
* `yq`. See link:https://github.com/mikefarah/yq/#install[Install.]

==== Procedure

. Run the link:../scripts/install-rhdh-catalog-source.sh[installation script] to create the RHDH Operator catalog resources in your cluster. By default, it installs the Release Candidate or GA version (from the `release-1.yy` branch), but the `--next` option allows to install the current development build (from the `main` branch).
+
The script auto-detects OLM v0 vs v1 from the ClusterExtension CRD (`--olm-version auto|v0|v1`). On OLM v1 it creates a `ClusterCatalog` / `ClusterExtension` and waits until the catalog is Serving and the extension is Installed (and for RHDH, until the `backstages.rhdh.redhat.com` CRD exists) before exiting successfully. On OpenShift, OLM v1 also merges internal-registry credentials into the cluster pull secret (`openshift-config/pull-secret`), matching the approach used by `prepare-restricted-environment.sh`, because catalogd authenticates via that global secret. On failure it prints diagnostics and exits non-zero. For example:
+
[source,console]
----
cd /tmp
curl -sSLO https://raw.githubusercontent.com/redhat-developer/rhdh-operator/main/.rhdh/scripts/install-rhdh-catalog-source.sh
chmod +x install-rhdh-catalog-source.sh

# install catalog and operator, for the latest downstream stable, RC or GA build from the release-1.yy branch
./install-rhdh-catalog-source.sh --latest --install-operator rhdh

# OR, install catalog and operator, for the next downstream CI build from the main branch
./install-rhdh-catalog-source.sh --next --install-operator rhdh

# Force classic OLM v0 (CatalogSource + Subscription) if needed
./install-rhdh-catalog-source.sh --next --install-operator rhdh --olm-version v0
----

. If you did not install the operator in the previous step (`--install-operator`), you can do so now. On OpenShift with OLM v0, open the *Administrator* perspective of the web console, then go to *Operators* → *OperatorHub*, search for Red Hat Developer Hub, and install the Red Hat Developer Hub Operator. For more info, see link:https://docs.openshift.com/container-platform/4.14/operators/admin/olm-adding-operators-to-cluster.html#olm-installing-from-operatorhub-using-web-console_olm-adding-operators-to-a-cluster[Installing from OperatorHub using the web console].

=== Deploying RHDH

Now that the Operator is installed and running, we can deploy an instance of RHDH by creating a Custom Resource (CR).

==== OpenShift

Just create a CR in any namespace and it should work out of the box. See the link:../../examples[examples].

==== Kubernetes

To enable pulling the PostgreSQL image from the link:https://catalog.redhat.com/[Red Hat Ecosystem Catalog], you will need to register an account on `registry.redhat.io` and add an image pull secret to the default service account within the namespace where RHDH is being deployed.

More details on link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication].

*Procedure*

. Create an image pull secret:
+
[source,console]
----
# Replace $YOUR_NS with your own namespace
kubectl -n "$YOUR_NS" create secret docker-registry rh-pull-secret \
    --docker-server=registry.redhat.io \
    --docker-username=<user_name> \
    --docker-password=<password> \
    --docker-email=<email>
----

. Add the pull secret to the namespace default service account
+
[source,console]
----
# Replace $YOUR_NS with your own namespace
$ kubectl -n "$YOUR_NS" patch serviceaccount default \
    -p '{"imagePullSecrets": [{"name": "rh-pull-secret"}]}'
----

. Create a CR. See the link:../../examples[examples].
