# Configuration for the golangci-lint tool - ensuring that dot imports do not trigger an ST1001 warning.

version: "2"

linters:
  enable:
    - staticcheck
  exclusions:
    rules:
      - path: tests/
        linters:
          - staticcheck
        text: "ST1001:"
      - path: integration_tests/
        linters:
          - staticcheck
        text: "ST1001:"