[jira]
jira_base_url = "https://redhat.atlassian.net"

[github_app]
# what should be launched automatically
pr_commands = [
    "/agentic_review",
    "/agentic_describe --pr_description.final_update_message=false",
    "/generate_labels",
]

[pr_test]
enable=false

[review_agent]
comments_location_policy = "summary"

[checks]
enable_auto_checks_feedback = "true"
persistent_comment = "true"
final_update_message = "false"

[config]
ignore_pr_authors = ["renovate"]

[rag_arguments]
enable_rag=true
rag_repo_list=['redhat-developer/rhdh','redhat-developer/red-hat-developers-documentation-rhdh','redhat-developer/rhdh-operator','redhat-developer/rhdh-chart']
