apiVersion: v1
kind: ConfigMap
metadata:
  name: default-dynamic-plugins
data:
  dynamic-plugins.yaml: |
    plugins:
      - package: 'ref://red-hat-developer-hub-backstage-plugin-orchestrator'
        enabled: true
      - package: 'ref://red-hat-developer-hub-backstage-plugin-orchestrator-backend'
        enabled: true
        dependencies:
          - ref: sonataflow
      - package: 'ref://red-hat-developer-hub-backstage-plugin-scaffolder-backend-module-orchestrator'
        enabled: true
      - package: 'ref://red-hat-developer-hub-backstage-plugin-orchestrator-form-widgets'
        enabled: true
