apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backstage-operator
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: backstage-operator
    app.kubernetes.io/instance: backstage-operator-metrics-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: backstage-operator
  name: backstage-operator-metrics-service
spec:
  ports:
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: metrics
  selector:
    app: backstage-operator
status:
  loadBalancer: {}
