# permissions for end users to edit backstages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: backstage-operator
    app.kubernetes.io/managed-by: kustomize
  name: backstage-viewer-role
rules:
- apiGroups:
  - rhdh.redhat.com
  resources:
  - backstages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rhdh.redhat.com
  resources:
  - backstages/status
  verbs:
  - get
