---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: orchestrator-gitops
  namespace: {{backstage-ns}}
spec:
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  sourceRepos:
  - '*'