apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        # Lightspeed Core Backend
        - name: lightspeed-core
          image: quay.io/lightspeed-core/lightspeed-stack:dev-20260811-0da4b12
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: lcs-backend
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          args:
            - "--synthesized-config-output"
            - "/tmp/.generated/run.yaml"
          env:
            - name: HF_HOME
              value: /tmp/hf_cache
          volumeMounts:
            - mountPath: /tmp
              name: lightspeed-data

      volumes:
        - name: lightspeed-data
          emptyDir: { }
