apiVersion: v1
kind: ConfigMap
metadata:
  name: default-dynamic-plugins
data:
  dynamic-plugins.yaml: |
    plugins:
      # Intelligent Assistant Plugins
      - package: 'ref://red-hat-developer-hub-backstage-plugin-intelligent-assistant'
        enabled: true

      - package: 'ref://red-hat-developer-hub-backstage-plugin-intelligent-assistant-backend'
        enabled: true
