apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  labels:
    app: rhdh-operator
    app.kubernetes.io/part-of: rhdh
spec:
  selector:
    matchLabels:
      app: rhdh-operator
  template:
    metadata:
      labels:
        app: rhdh-operator
        app.kubernetes.io/component: rhdh-operator
    spec:
      containers:
        - name: manager
          env:
            - name: OPERATOR_NAME
              value: rhdh-operator
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RELATED_IMAGE_postgresql
              value: quay.io/fedora/postgresql-15:latest
            - name: RELATED_IMAGE_backstage
              value: quay.io/rhdh-community/rhdh:next
          volumeMounts:
            - mountPath: /default-config/flavours/lightspeed
              name: flavour-lightspeed-config
            - mountPath: /default-config/flavours/orchestrator
              name: flavour-orchestrator-config
      volumes:
        - name: flavour-lightspeed-config
          configMap:
            name: flavour-lightspeed-config
        - name: flavour-orchestrator-config
          configMap:
            name: flavour-orchestrator-config