apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rhdh-operator
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: rhdh-operator
    app.kubernetes.io/instance: rhdh-operator-metrics-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: rhdh-operator
  name: rhdh-operator-metrics-service
spec:
  ports:
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: metrics
  selector:
    app: rhdh-operator
status:
  loadBalancer: {}
