apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{PROFILE_SHORT}}-operator
spec:
  channel: {{DEFAULT_CHANNEL}}
  installPlanApproval: Automatic
  name: {{BUNDLE_METADATA_PACKAGE_NAME}}
  source: {{PROFILE_SHORT}}-operator
  sourceNamespace: {{OLM_NAMESPACE}}
  startingCSV: {{PROFILE_SHORT}}-operator.v{{VERSION}}