apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{PROFILE_SHORT}}-operator
spec:
  sourceType: grpc
  image: {{CATALOG_IMG}}
  displayName: "Upstream Backstage Operator (profile: {{PROFILE}})"