apiVersion: rhdh.redhat.com/v1alpha5
kind: Backstage
metadata:
  name: my-backstage
spec:
  application:
    extraEnvs:
      envs:
        - name: CATALOG_INDEX_IMAGE
          value: "quay.io/rhdh/plugin-catalog-index:1.9"
          containers:
            - install-dynamic-plugins

