apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic-plugins
data:
  dynamic-plugins.yaml: |
    plugins:
      - package: 'ref://backstage-community-plugin-catalog-backend-module-keycloak-dynamic'
        enabled: true
---
apiVersion: rhdh.redhat.com/v1alpha5
kind: Backstage
metadata:
  name: bs1
spec:
  application:
    dynamicPluginsConfigMapName: dynamic-plugins

