apiVersion: v1
kind: ConfigMap
metadata:
  name: cm1
data:
  ENV_CM1: "cm1"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm2
data:
  ENV_CM2: "cm2"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm3
data:
  ENV_CM3_1: "cm3-1"
  ENV_CM3_2: "cm3-2"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret1
stringData:
  ENV1: "secret1"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret2
stringData:
  ENV2: "secret2"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret3
stringData:
  ENV3: "secret3"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: no-plugins
data:
  dynamic-plugins.yaml: "includes: []\nplugins: []\n"
---
apiVersion: rhdh.redhat.com/v1alpha4
kind: Backstage
metadata:
  name: my-rhdh-envs
spec:
  deployment:
    patch:
      spec:
        template:
          spec:
            containers:
              - name: sidecar
                image: busybox
                command: ["sh", "-c", "while true; do echo 'Container is running...'; sleep 5; done"]
  application:
    dynamicPluginsConfigMapName: no-plugins
    extraEnvs:
      envs:
        - name: ENV4 # in backstage-backend container only
          value: "env4"
        - name: ENV5  # only in install-dynamic-plugins container
          value: "env5"
          containers:
            - sidecar
        - name: ENV6 # in all containers
          value: "env6"
          containers:
            - "*"
      configMaps:
        - name: cm1 # ENV_CM1 in backstage-backend only
        - name: cm2 # ENV_CM2 in all containers
          containers:
            - "*"
        - name: cm3  # ENV_CM3_1 in sidecar only
          key: ENV_CM3_1
          containers:
            - sidecar
      secrets:
        - name: secret1
          key: ENV1
        - name: secret2
          containers:
            - sidecar
        - name: secret3
          containers:
            - "*"


