apiVersion: v1
kind: Secret
metadata:
  name: lightspeed-secrets
type: Opaque
stringData:
  VLLM_URL: ""
  VLLM_API_KEY: ""
  VLLM_MAX_TOKENS: ""
  VLLM_TLS_VERIFY: ""
  OPENAI_API_KEY: ""
  VERTEX_AI_PROJECT: ""
  VERTEX_AI_LOCATION: ""
  GOOGLE_APPLICATION_CREDENTIALS_HOST_PATH: ""
  GOOGLE_APPLICATION_CREDENTIALS: ""
  OLLAMA_URL: ""
  ENABLE_VALIDATION: ""
  VALIDATION_PROVIDER: ""
  VALIDATION_MODEL_NAME: ""
  LLAMA_STACK_LOGGING: ""
  OTEL_SDK_DISABLED: ""
---
apiVersion: rhdh.redhat.com/v1alpha5
kind: Backstage
metadata:
  name: lightspeed-test
spec:
  application:
    extraEnvs:
      secrets:
        - name: lightspeed-secrets
          containers:
            - lightspeed-core

