apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-plugin
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: "@redhat/backstage-plugin-orchestrator@1.6.0"
        disabled: false
      - package: "@redhat/backstage-plugin-orchestrator-backend-dynamic@1.6.0"
        disabled: false
        dependencies:
          - ref: sonataflow
      - package: "@redhat/backstage-plugin-scaffolder-backend-module-orchestrator-dynamic@1.6.0"
        disabled: false
      - package: "@redhat/backstage-plugin-orchestrator-form-widgets@1.6.0"
        disabled: false      
      - package: ./dynamic-plugins/dist/backstage-community-plugin-redhat-argocd
        disabled: false
        dependencies:
          - ref: gitops
      - package: ./dynamic-plugins/dist/backstage-community-plugin-tekton
        disabled: false
        dependencies:
          - ref: tekton
      - package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd-backend-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-argocd-dynamic
        disabled: false