###
# This assumes you have a mirror registry reachable at registry.localhost:5000 from your host (or bastion host) and from your cluster.
# Feel free to copy this and adapt to your environment.
#
# 1. Use the .rhdh/scripts/mirror-plugins.sh to mirror a plugin catalog index image before applying the manifest here:
# ```
# .rhdh/scripts/mirror-plugins.sh \
#    --plugin-index oci://registry.access.redhat.com/rhdh/plugin-catalog-index:<tag> \
#    --to-registry registry.localhost:5000
#
# kubectl apply -f examples/plugin-mirroring.yaml
# ```

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-rhdh-mirror-conf
data:
  "rhdh-registries.conf": |
    [[registry]]
    location = "registry.localhost:5000"
    insecure = true

    [[registry]]
    # GA and TP plugins
    prefix = "registry.access.redhat.com/rhdh"
    location = "registry.localhost:5000/rhdh"
    insecure = true
    
    [[registry]]
    # Some plugins might be available here
    prefix = "quay.io/rhdh"
    location = "registry.localhost:5000/rhdh"
    insecure = true

    [[registry]]
    # RHDH community plugins
    prefix = "ghcr.io/redhat-developer/rhdh-plugin-export-overlays"
    location = "registry.localhost:5000/rhdh-plugin-export-overlays"
    insecure = true

---
apiVersion: rhdh.redhat.com/v1alpha5
kind: Backstage
metadata:
  name: my-rhdh-plugin-mirroring
spec:
  application:
    extraFiles:
      configMaps:
        - name: my-rhdh-mirror-conf
          key: rhdh-registries.conf
          mountPath: /etc/containers/registries.conf.d
          containers: [ install-dynamic-plugins ]

#    extraEnvs:
#      envs:
#        # Set the CATALOG_INDEX_IMAGE env var to your mirrored catalog index image
#        # if you are using a tag/digest different from the default
#        - name: CATALOG_INDEX_IMAGE
#          value: registry.localhost:5000/rhdh/plugin-catalog-index:<tag>
#          containers: [ install-dynamic-plugins ]
