apiVersion: v1
kind: ConfigMap
metadata:
  name: my-dynamic-plugins-pvc-dp-cache
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      # Enable Bulk import plugins.
      - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-bulk-import
        disabled: false

---
apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: my-rhdh-pvc-dp-cache
spec:
  application:
    dynamicPluginsConfigMapName: my-dynamic-plugins-pvc-dp-cache
  deployment:
    patch:
      spec:
        replicas: 2
        template:
          spec:
            # Avoid (if possible) scheduling multiple replicas on the same node.
            # This is to test the fact that each pod gets its own stable dynamic plugins cache storage on a multi-node cluster.
            affinity:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      labelSelector:
                        matchLabels:
                          rhdh.redhat.com/app: backstage-my-rhdh-pvc-dp-cache
                      topologyKey: kubernetes.io/hostname
            volumes:
              - $patch: replace
                name: dynamic-plugins-root
                persistentVolumeClaim:
                  claimName: dynamic-plugins-root
        updateStrategy:
          type: RollingUpdate
        volumeClaimTemplates:
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: dynamic-plugins-root
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 2Gi
