#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: dynamic-plugins-root
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 2Gi
---
apiVersion: rhdh.redhat.com/v1alpha5
kind: Backstage
metadata:
  name: bs1
spec:
  deployment:
    kind: StatefulSet
    patch:
      spec:
        replicas: 2
        template:
          spec:
            # uncomment the following nodeAffinity section to schedule pods on a specific node
            # and make sure to replace the value with the desired node name (ip-10-0-1-128.ec2.internal in this example)
            # to be able to test the ReadWriteOnce PVC on a multi node cluster
            # affinity:
            #   nodeAffinity:
            #     requiredDuringSchedulingIgnoredDuringExecution:
            #       nodeSelectorTerms:
            #         - matchExpressions:
            #             - key: kubernetes.io/hostname
            #               operator: In
            #               values:
            #                 - ip-10-0-1-156.ec2.internal
            volumes:
              - $patch: replace
                name: dynamic-plugins-root
                persistentVolumeClaim:
                  claimName: dynamic-plugins-root
        updateStrategy:
          type: RollingUpdate
        volumeClaimTemplates:
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: dynamic-plugins-root
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
  application:
    dynamicPluginsConfigMapName: dynamic-plugins

