apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: lightspeed-core
          args:
            - "--config"
            - "/app-root/lightspeed-stack-okp.yaml"
            - "--synthesized-config-output"
            - "/tmp/.generated/run.yaml"
          {{- if eq .Rhdh.Runtime.Platform "ocp"}}
          env:
            - name: OKP_SERVICE_URL
              value: "http://ia-okp-{{.Rhdh.Name}}-{{.Rhdh.Namespace}}.{{.Rhdh.Runtime.IngressDomain}}"
          {{- end}}
