name: Docker Build
description: Docker Build
inputs:
  registry:
    description: The registry to push to
    required: true
  password:
    description: The password to use for the registry
    required: true
  username:
    description: The username to use for the registry
    required: true
  imageName:
    description: The name of the image to build
    required: true
  imageTags:
    description: The tags to apply to the image
    required: true
  imageLabels:
    description: The labels for the Docker image
    required: false
  push:
    description: Whether to push the image
    required: true
  dockerfile:
    description: path to dockerfile to build
    required: true

runs:
  using: composite
  steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: false
        swap-storage: false

    - name: Set up QEMU
      uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a # v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3

    - name: Cache Docker layers
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to the Container registry
      if: ${{ inputs.push }}
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.imageName }}
        tags: |
          ${{ inputs.imageTags }}
        labels: |
          ${{ inputs.imageLabels }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        provenance: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      name: Move cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
