apiVersion: v1
kind: Namespace
metadata:
  name: openshift-serverless
  labels:
    rhdh.redhat.com/managed-by: plugin-infra
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: serverless-operator-group
  namespace: openshift-serverless
  labels:
    rhdh.redhat.com/managed-by: plugin-infra
spec:
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: serverless-operator
  namespace: openshift-serverless
  labels:
    rhdh.redhat.com/managed-by: plugin-infra
spec:
  channel: stable
  installPlanApproval: Automatic
  name: serverless-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
