apiVersion: v1
kind: Namespace
metadata:
  name: openshift-serverless-logic
  labels:
    rhdh.redhat.com/managed-by: plugin-infra
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-serverless-logic
  namespace: openshift-serverless-logic
  labels:
    rhdh.redhat.com/managed-by: plugin-infra
spec:
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: logic-operator
  namespace: openshift-serverless-logic
  labels:
    rhdh.redhat.com/managed-by: plugin-infra
spec:
  channel: stable  #  channel of an operator package to subscribe to
  installPlanApproval: Automatic #  whether the update should be installed automatically
  name: logic-operator  #  name of the operator package
  source: redhat-operators  #  name of the catalog source
  sourceNamespace: openshift-marketplace
  startingCSV: logic-operator.v1.38.0  # The initial version of the operator
