apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipelines-operator-installer
  namespace: openshift-operators
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipelines-operator-installer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: plugin-infra-olm-v1-installer-role
subjects:
  - kind: ServiceAccount
    name: pipelines-operator-installer
    namespace: openshift-operators
---
apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: openshift-pipelines-operator
spec:
  namespace: openshift-operators
  serviceAccount:
    name: pipelines-operator-installer
  source:
    sourceType: Catalog
    catalog:
      packageName: openshift-pipelines-operator-rh
      channels:
        - pipelines-1.21
      selector:
        matchLabels:
          olm.operatorframework.io/metadata.name: openshift-redhat-operators
  install:
    preflight:
      crdUpgradeSafety:
        enforcement: None
