name: 'Pre-load images into Kind cluster'
description: 'Extracts operator and operand images from manifests and pre-loads them into a Kind cluster'

inputs:
  manifests:
    description: 'Space-separated list of manifest URLs or file paths to extract images from'
    required: true
  kind-cluster-name:
    description: 'Name of the Kind cluster to load images into'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Pre-load operator and operand images into Kind cluster
      shell: bash
      run: |
        extract_images() {
          local manifest="$1"
          local content
          # Check if it's a URL or a local file path
          if [[ "${manifest}" =~ ^https?:// ]]; then
            content=$(curl -s "${manifest}")
          else
            content=$(cat "${manifest}")
          fi
          echo "${content}" | yq -r '
            # Extract RELATED_IMAGE_* env var values
            (select(.kind == "Deployment") | .spec.template.spec.containers[]?.env[]? | select(.name | test("^RELATED_IMAGE_")) | .value),
            # Extract container images
            (select(.kind == "Deployment") | .spec.template.spec.containers[]?.image)
          ' | grep -v '^null$' | grep -v '^\$' | grep -v '^$' | sort -u
        }

        ALL_IMAGES=""
        for manifest in ${{ inputs.manifests }}; do
          echo "--- Extracting images from manifest: ${manifest}"
          IMAGES=$(extract_images "${manifest}")
          echo "\tImages found:"
          echo "${IMAGES}"
          ALL_IMAGES="${ALL_IMAGES}
        ${IMAGES}"
        done

        # Deduplicate all images
        ALL_IMAGES=$(echo "${ALL_IMAGES}" | grep -v '^$' | sort -u)
        echo "--- All unique images to pre-load:"
        echo "${ALL_IMAGES}"

        # Pull and load each image directly into Kind using docker
        for img in ${ALL_IMAGES}; do
          echo "\t--- Pulling image: ${img}"
          docker pull "${img}" || { echo "Warning: Failed to pull ${img}"; continue; }
          echo "\t--- Loading image into Kind: ${img}"
          kind load docker-image "${img}" --name ${{ inputs.kind-cluster-name }} || echo "Warning: Failed to load ${img}"
          docker image rm -f "${img}" || echo "Warning: Failed to remove ${img}"
        done
