name: Lint Config Checks

on:
  push:
    paths:
      - '.golangci.yml'
      - '.github/workflows/lint-config-checks.yaml'
    branches: [ main ]
  pull_request:
    paths:
      - '.golangci.yml'
      - '.github/workflows/lint-config-checks.yaml'
    branches: [ main ]

jobs:
  lint-config-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: 'go.mod'

      - name: Verify linter configuration
        run: make lint-config
