name: Plugin Installer CI

on:
  push:
    branches:
      - main
      - 'release-[2-9]+.[0-9]+'
    paths:
      - 'plugin-installer/**'
      - '.github/workflows/plugin-installer.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'plugin-installer/**'
      - '.github/workflows/plugin-installer.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ${{ vars.REGISTRY }}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install skopeo

      - name: Run tests
        run: RUN_INTEGRATION_TESTS=true ./plugin-installer/install_plugins_test.sh

  build:
    name: Build image
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build image (PR validation)
        if: github.event_name == 'pull_request'
        run: make install-dp-build

      - name: Set up QEMU
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3

      - name: Set up Docker Buildx
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - name: Login to registry (${{ env.REGISTRY }})
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push multiplatform image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: make install-dp-buildx
