name: PR TOML Validator

on:
  push:
    paths:
      - '**.toml'
  pull_request:
    paths:
      - '**.toml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: tombi-toml/setup-tombi@6b212641348ff5d87e27ea3e63ccb751d880eaf0 # v1
      - name: Validate TOML files
        run: tombi lint