apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      initContainers:
        - name: init-rag-data
          image: quay.io/redhat-ai-dev/rag-content:release-1.9-lls-0.5.0
          command:
            - "sh"
            - "-c"
            - "echo 'Copying RAG data...'; cp -r /rag/. /data/ && chmod -R 777 /data/vector_db && echo 'Copy complete.'"
          resources:
            requests:
              memory: 150Mi
              cpu: 50m
            limits:
              memory: 500Mi
              cpu: 100m
          volumeMounts:
            - mountPath: /data
              name: rag-data-volume

      containers:
        # Lightspeed Core Backend
        - name: lightspeed-core
          image: quay.io/lightspeed-core/lightspeed-stack:0.5.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: lcs-backend
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          volumeMounts:
            - mountPath: /tmp/data/feedback
              name: shared-storage
            - mountPath: /rag-content
              name: rag-data-volume
            - mountPath: /tmp              # Add this to make /tmp writable
              name: temp

      volumes:
        - name: shared-storage
          emptyDir: { }
        - name: rag-data-volume
          emptyDir: { }
