apiVersion: v1
kind: ConfigMap
metadata:
  name: default-dynamic-plugins
data:
  dynamic-plugins.yaml: |
    plugins:
      # Lightspeed Plugins
      - package: 'oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-lightspeed:{{inherit}}'
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              red-hat-developer-hub.backstage-plugin-lightspeed:
                translationResources:
                  - importName: lightspeedTranslations
                    module: Alpha
                    ref: lightspeedTranslationRef
                dynamicRoutes:
                  - path: /lightspeed
                    importName: LightspeedPage
                mountPoints:
                  - mountPoint: application/listener
                    importName: LightspeedFAB
                  - mountPoint: application/provider
                    importName: LightspeedDrawerProvider
                  - mountPoint: application/internal/drawer-state
                    importName: LightspeedDrawerStateExposer
                    config:
                      id: lightspeed
                  - mountPoint: application/internal/drawer-content
                    importName: LightspeedChatContainer
                    config:
                      id: lightspeed
                      priority: 100
      - package: 'oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-lightspeed-backend:{{inherit}}'
        disabled: false
