# Lightspeed (AI) flavour metadata
# This flavour is enabled by default and provides AI/Lightspeed functionality
# FIXME: temporarily disabled due to DPDY issues; to re-enable in https://redhat.atlassian.net/browse/RHIDP-15458
enabledByDefault: false
